---
- name: Creates directory
  ansible.builtin.file:
    path: "{{ file_path }}"
    state: directory
    mode: "0777"
    recurse: true
  become: true
  delegate_to: localhost

- name: Include selinux role
  vars:
    selinux_fcontexts:
      - {target: '{{ file_path }}(/.*)?', setype: 'httpd_sys_content_t', state: 'present'}
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.selinux

- name: Ensure Nginx container is running
  containers.podman.podman_container:
    name: nginx_container
    image: docker.io/nginx:stable-alpine3.17-slim
    state: started
    ports:
      - "{{ web_port }}:80"
    volumes:
      - "{{ file_path }}:/usr/share/nginx/html:Z"
    recreate: true

- name: Create HTML report
  ansible.builtin.template:
    src: report.j2
    dest: "{{ file_path }}/index.html"
    mode: "0777"
    #mode: "644"
  delegate_to: localhost

- name: Copy CSS over
  ansible.builtin.copy:
    src: "css"
    dest: "{{ file_path }}"
    directory_mode: true
    mode: "0777"
  delegate_to: localhost

- name: Copy CSS over
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ file_path }}"
    directory_mode: true
    mode: "0777"
    #mode: "644"
  delegate_to: localhost
  loop:
    - "webpage_logo.png"
    - "redhat-ansible-logo.svg"
    - "router.png"

- name: Retrieve public IP address
  ansible.builtin.command: curl https://ifconfig.me
  register: public_ip_report
  ignore_errors: true

- name: Display link to inventory report
  ansible.builtin.debug:
    msg:
      - "Please go to http://{{ public_ip_report.stdout | default(ansible_fqdn) }}:{{ web_port }}"
